config/routes.rb
Spree::Core::Engine.routes.draw do
  
  namespace :admin do
    resource :store_settings
    resources :posts do
      resources :images, :controller => 'posts/images' do
        post :update_positions, :on => :collection
      end
      post :update_positions, :on => :collection
      get :published, :on => :member
      get :unpublished, :on => :member
    end
    
    resources :static_pages do
      resources :images, :controller => 'static_pages/images' do
        post :update_positions, :on => :collection
      end
      post :update_positions, :on => :collection
      get :published, :on => :member
      get :unpublished, :on => :member
    end
    
    resources :uploads do
      post :update_positions, :on => :collection
    end
    
    resources :taxonomy_posts do
    	collection do
    		post :update_positions
    	end
      member do
        get :get_children
      end

      resources :taxon_posts
    end

    resources :taxon_posts, :only => [] do
      collection do
        get :search
      end
    end
  end
  
  match '/contacts', :to => 'static_pages#contacts', :as => :contacts
  match '/contacts/send', :to => "static_pages#create_mail", :via => :post
  match '/p/:id', :to => 'static_pages#show', :as => :page
  match '/p', :to => 'static_pages#index', :as => :pages
  match '/blog', :to => 'posts#index', :as => :blog
  match '/news/:id', :to => 'posts#show', :as => :post
  
  # route globbing for pretty nested taxon and product paths
  match '/tp/*id', :to => 'taxon_posts#show', :as => :nested_taxon_posts
end

app/models/spree/taxonomy_post.rb
module Spree
  class TaxonomyPost < ActiveRecord::Base
    validates :name, :presence => true

    has_many :taxon_posts
    has_one :root, :conditions => { :parent_id => nil }, :class_name => "Spree::TaxonPost",
                   :dependent => :destroy

    after_save :set_name

    default_scope :order => "#{self.table_name}.position"

    private
      def set_name
        if root
          root.update_column(:name, name)
        else
          self.root = TaxonPost.create!({ :taxonomy_post_id => id, :name => name }, :without_protection => true)
        end
      end

  end
end

app/controllers/spree/admin/taxonomy_posts_controller.rb
module Spree
  module Admin
    class TaxonomyPostsController < ResourceController
      respond_to :json, :only => [:get_children]

      def get_children
        @taxon_posts = TaxonPost.find(params[:parent_id]).children

        respond_with(@taxon_posts)
      end

      private

      def location_after_save
        if @taxonomy_post.created_at == @taxonomy_post.updated_at
          edit_admin_taxonomy_post_url(@taxonomy_post)
        else
          admin_taxonomy_posts_url
        end
      end
    end
  end
end

app/views/spree/admin/taxonomy_posts/_form.html.erb
<div data-hook="admin_inside_taxonomy_post_form" class="field align-center">
  <%= f.field_container :name do %>
    <%= f.label :name, t(:name) %> <span class="required">*</span><br />
    <%= error_message_on :taxonomy_post, :name, :class => 'fullwidth title' %>
    <%= text_field :taxonomy_post, :name %>
  <% end %>
</div>

app/views/spree/admin/taxonomy_posts/_js_head.html.erb
<% content_for :head do %>
  <%= javascript_tag "var taxonomy_post_id = #{@taxonomy_post.id};
    var loading = '#{escape_javascript t(:loading)}';
    var new_taxon_post = '#{escape_javascript t(:new_taxon_post)}';
    var server_error = '#{escape_javascript t(:server_error)}';
    var taxonomy_post_tree_error = '#{escape_javascript t(:taxonomy_post_tree_error)}';"
  %>
<% end %>

app/views/spree/admin/taxonomy_posts/_list.html.erb
<table class="index sortable" id='listing_taxonomy_posts' data-hook data-sortable-link="<%= update_positions_admin_taxonomy_posts_url %>">
  <colgroup>
    <col style="width: 85%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="taxonomy_posts_header">
      <th><%= t(:name) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @taxonomy_posts.each do |taxonomy_post| %>
      <tr id="<%= spree_dom_id taxonomy_post %>" data-hook="taxonomy_posts_row" class="<%= cycle('odd', 'even')%>">
        <td>
          <span class="handle"></span>
          <%= taxonomy_post.name %>
        </td>
        <td class="actions">
          <%= link_to_edit taxonomy_post.id, :no_text => true %>
          <%= link_to_delete taxonomy_post, :no_text => true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/taxonomy_posts/_taxon.html.erb
<% if taxon.children.length != 0 %>
  <ul>
    <% taxon.children.each do |child| %>
      <li id="<%= child.id %>" rel="taxon">
        <a style="background-image: url(<%= child.icon.url %>);" href="#"><%= child.name %></a>
        <% if child.children.length > 0 %>
          <%= render :partial => 'taxon', :locals => { :taxon => child } %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/spree/admin/taxonomy_posts/edit.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<%= render :partial => 'js_head' %>

<% content_for :page_title do %>
  <%= t(:taxonomy_post_edit) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:back_to_taxonomy_posts_list), spree.admin_taxonomy_posts_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<div id="ajax_error" class="errorExplanation" style="display:none;"></div>

<%= form_for [:admin, @taxonomy_post] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div>
      <%= label_tag nil, t(:tree) %><br />
      <div id="taxonomy_post_tree" class="tree" data-url="<%= admin_taxonomy_post_taxon_posts_path @taxonomy_post %>"></div>
    </div>
    <div id="progress" style="display:none;">
      <%= image_tag 'spinner.gif', :title => 'Spinner', :style => "vertical-align:bottom;" %> <%= t(:updating) %>..
    </div>

    <div class="info"><%= t(:taxonomy_post_tree_instruction) %></div>

    <br>

    <div class="filter-actions actions">
      <%= button t(:update), 'icon-refresh' %>
      <span class="or"><%= t(:or) %></span>
      <%= button_link_to t(:cancel), admin_taxonomy_posts_path, :icon => 'icon-remove' %>
    </div>
  </fieldset>
<% end %>

<% content_for :head do %>
  <%= javascript_tag do -%>
    var initial = [
      { "attr" :
      { "id" : "<%= @taxonomy_post.root.id %>", "rel" : "root" },
      "data" : "<%= escape_javascript(raw(@taxonomy_post.root.name)) %>",
      "state" : "open",
      "children" : [
        <% @taxonomy_post.root.children.each_with_index do |taxon_post,i| %>
          {
            "attr" :
            { "id" : "<%= taxon_post.id %>"},
            "data" : "<%= escape_javascript(raw(taxon_post.name)) %>"
            <% unless taxon_post.children.empty? %>
              ,"state" : "closed"
            <% end %>
          }<%= ',' if i < (@taxonomy_post.root.children.size - 1) %>
        <% end %>
      ]
        }
    ];
  <% end -%>
<% end %>

app/views/spree/admin/taxonomy_posts/get_children.json.erb
[<% @taxon_posts.each_with_index do |t,i| %>
  { "attr" :
    { "id" : "<%= t.id %>" },
    "data" : "<%= raw(t.name.gsub('"','\"')) %>"
    <% unless t.children.empty? %>
      ,"state" : "closed"
    <% end %>
  }<%= "," if i < (@taxon_posts.size - 1) %>
<% end %>]

app/views/spree/admin/taxonomy_posts/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:taxonomy_posts) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:new_taxonomy_post), spree.new_admin_taxonomy_post_url, :icon => 'icon-plus', :id => 'admin_new_taxonomy_post_link' %></p>
  </li>
<% end %>

<div id='list-taxonomy_posts' data-hook>
  <%= render :partial => 'list' %>
</div>

app/views/spree/admin/taxonomy_posts/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:new_taxonomy_post) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:back_to_taxonomy_posts_list), spree.admin_taxonomy_posts_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= form_for [:admin, @taxonomy_post] do |f| %>

  <%= render :partial => 'form', :locals => { :f => f } %>
  <fieldset class="no-border-top">
    <br>
    <div class="filter-actions actions" data-hook="buttons">
      <%= button t(:create), 'icon-ok' %>
    </div>
  </fieldset>
<% end %>