config/routes.rb
Spree::Core::Engine.routes.draw do
  
  namespace :admin do
    resource :store_settings
    resources :posts do
      resources :images, :controller => 'posts/images' do
        post :update_positions, :on => :collection
      end
      post :update_positions, :on => :collection
      get :published, :on => :member
      get :unpublished, :on => :member
    end
    
    resources :static_pages do
      resources :images, :controller => 'static_pages/images' do
        post :update_positions, :on => :collection
      end
      post :update_positions, :on => :collection
      get :published, :on => :member
      get :unpublished, :on => :member
    end
    
    resources :uploads do
      post :update_positions, :on => :collection
    end
    
    resources :taxonomy_posts do
    	collection do
    		post :update_positions
    	end
      member do
        get :get_children
      end

      resources :taxon_posts
    end

    resources :taxon_posts, :only => [] do
      collection do
        get :search
      end
    end
  end
  
  match '/contacts', :to => 'static_pages#contacts', :as => :contacts
  match '/contacts/send', :to => "static_pages#create_mail", :via => :post
  match '/p/:id', :to => 'static_pages#show', :as => :page
  match '/p', :to => 'static_pages#index', :as => :pages
  match '/blog', :to => 'posts#index', :as => :blog
  match '/news/:id', :to => 'posts#show', :as => :post
  
  # route globbing for pretty nested taxon and product paths
  match '/tp/*id', :to => 'taxon_posts#show', :as => :nested_taxon_posts
end

app/models/spree/post.rb
module Spree
  class Post < Blog
    has_and_belongs_to_many :products, :join_table => 'spree_posts_products'
    has_and_belongs_to_many :taxons, :join_table => 'spree_posts_taxons'
    acts_as_commentable
    
    has_and_belongs_to_many :taxon_posts, :join_table => "spree_posts_taxon_posts", :class_name => "Spree::TaxonPost"
    
    scope :published, lambda { where("published_at <= '#{Time.now}' AND active = 1") }
    scope :valid, lambda { where("from <= #{Time.now} AND to >= #{Time.now}") }
    
  end
end

app/controllers/spree/admin/posts/images_controller.rb
module Spree
  module Admin
    module Posts
      class ImagesController < ResourceController
        before_filter :load_data

        create.before :set_viewable
        update.before :set_viewable
        destroy.before :destroy_before

        private

        def location_after_save
          admin_post_images_url(@post)
        end

        def load_data
          @post = Spree::Post.find_by_permalink(params[:post_id])
          @posts = [@post.title, @post.id]
        end

        def set_viewable
          @image.viewable_type = 'Spree::Blog'
          @image.viewable_id = params[:image][:viewable_id]
        end

        def destroy_before
          @viewable = @image.viewable
        end

      end
    end
  end
end

app/controllers/spree/admin/posts_controller.rb
module Spree
  module Admin
    class PostsController < ResourceController
      def index
        respond_with(@collection) do |format|
          format.html
          format.json { render :json => json_data }
        end
      end

      def show
        redirect_to( :action => :edit )
      end
      
      def destroy
        @post = Post.where(:permalink => params[:id]).first!
        @post.delete

        flash.notice = I18n.t('notice_messages.post_deleted')

        respond_with(@post) do |format|
          format.html { redirect_to collection_url }
          format.js  { render_js_for_destroy }
        end
      end
      
      def published
        @post = Post.where(:permalink => params[:id]).first!
        @post.update_attribute(:published_at, Time.now)
        
        flash.notice = I18n.t('notice_messages.post_published')
        
        respond_with(@post) do |format|
          format.html { redirect_to collection_url }
        end
      end
      
      def unpublished
        @post = Post.where(:permalink => params[:id]).first!
        @post.update_attribute(:published_at, nil)
        
        flash.notice = I18n.t('notice_messages.post_unpublished')
        
        respond_with(@post) do |format|
          format.html { redirect_to collection_url }
        end
      end

      def clone
        @new = @post.duplicate

        if @new.save
          flash.notice = I18n.t('notice_messages.post_cloned')
        else
          flash.notice = I18n.t('notice_messages.post_not_cloned')
        end

        respond_with(@new) { |format| format.html { redirect_to edit_admin_post_url(@new) } }
      end

      protected
      def find_resource
        Spree::Post.find_by_permalink!(params[:id])
      end
      
      def location_after_save
        edit_admin_post_url(@post)
      end
      
      def collection
        return @collection if @collection.present?
        params[:q] ||= {}

        params[:q][:s] ||= "name asc"
        
        if !params[:q][:published_at_gt].blank?
          params[:q][:published_at_gt] = Time.zone.parse(params[:q][:published_at_gt]).beginning_of_day rescue ""
        end

        if !params[:q][:published_at_lt].blank?
          params[:q][:published_at_lt] = Time.zone.parse(params[:q][:published_at_lt]).end_of_day rescue ""
        end

        @search = super.ransack(params[:q])
        @collection = @search.result.page(params[:page]).per(12)
      end
    end
  end
end

app/controllers/spree/admin/static_pages/images_controller.rb
module Spree
  module Admin
    module StaticPages
      class ImagesController < ResourceController
        before_filter :load_data

        create.before :set_viewable
        update.before :set_viewable
        destroy.before :destroy_before

        private

        def location_after_save
          admin_static_page_images_url(@static_page)
        end

        def load_data
          @static_page = Spree::StaticPage.find_by_permalink(params[:static_page_id])
          @static_pages = [@static_page.title, @static_page.id]
        end

        def set_viewable
          @image.viewable_type = 'Spree::Page'
          @image.viewable_id = params[:image][:viewable_id]
        end

        def destroy_before
          @viewable = @image.viewable
        end

      end
    end
  end
end

app/controllers/spree/posts_controller.rb
module Spree
  class PostsController < BaseController
    before_filter :load_post, :only => :show
    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/taxons'

    respond_to :html
    
    def index
      @posts = Spree::Post.published.order('published_at desc').page(params[:page]).per(20)
      respond_with(@posts)
    end
    
    def show
      return unless @post
    end
    
    private
    def accurate_title
      @post ? @post.title : super
    end
    
    def load_post
      @post = Spree::Post.find_by_permalink!(params[:id])
    end
  end
end

app/helpers/spree/posts_helper.rb
module Spree
  module PostsHelper
    
    def preview_content(post, limit = 300)
      raw(truncate(strip_tags(post.body.strip).strip,:length => limit))
    end

    def post_date(post)
      post.published_at.strftime("%d/%m/%d %H:%M")
    end

    def tag_link(tag)
      link_to(tag.name, posts_path + "?tag=#{tag.name}")
    end

  end
end

app/views/spree/admin/posts/images/_form.html.erb
<div data-hook="admin_image_form_fields">
  <div class="four columns alpha">
    <div data-hook="file" class="field">
      <%= f.label t(:filename) %><br>
      <%= f.file_field :attachment %>
    </div>
    <div data-hook="variant" class="field">
      <%= f.label Spree::Post.model_name.human %><br>
      <%= f.select :viewable_id, @posts, {}, {:class => 'select2 fullwidth'} %>
    </div>
  </div>
  <div data-hook="alt_text" class="field omega five columns">
    <%= f.label t(:alt_text) %><br>
    <%= f.text_area :alt, :rows => 4, :class => 'fullwidth' %>
  </div>
</div>

<div class="clear"></div>

app/views/spree/admin/posts/images/edit.html.erb
<%= render :partial => 'spree/admin/shared/post_tabs', :locals => { :current => 'Images' } %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @post } %>

<% content_for :page_actions do %>
  <li><%= button_link_to t(:back_to_images_list), admin_post_images_url(@post), :icon => 'icon-arrow-left' %></li>
<% end %>

<%= form_for [:admin, @post, @image], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="edit_image">
    <legend align="center"><%= @image.attachment_file_name%></legend>
    <div data-hook="thumbnail" class="field alpha three columns align-center">
      <%= f.label t(:thumbnail) %><br>
      <%= link_to image_tag(@image.attachment.url(:small)), @image.attachment.url(:product) %>
    </div>
    <div class="nine columns omega">
      <%= render :partial => 'form', :locals => { :f => f } %>  
    </div>
    <div class="clear"></div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button t(:update), 'icon-refresh' %>
      <span class="or"><%= t(:or) %></span>
      <%= link_to t(:cancel), admin_post_images_url(@post), :id => 'cancel_link', :class => 'button icon-remove' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/posts/images/index.html.erb
<%= render :partial => 'spree/admin/shared/post_tabs', :locals => {:current => 'Images'} %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon('icon-plus', t(:new_image), new_admin_post_image_url(@post), :id => 'new_image_link', :class => 'button') %></li>
<% end %>

<div id="images" data-hook></div>

<% unless @post.images.any? %>
  <div class="no-objects-found">
    <%= t(:no_images_found) %>.
  </div>
<% else %>
  <table class="index sortable" data-hook="images_table" data-sortable-link="<%= update_positions_admin_post_images_url(@post) %>">
    <colgroup>
      <col style="width: 5%">
      <col style="width: 10%">
      <col style="width: 25%">
      <col style="width: 45%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="images_header">
        <th colspan="2"><%= t(:thumbnail) %></th>
        <th><%= @post.title %></th>
        <th><%= t(:alt_text) %></th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% @post.images.each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
            <span class="handle"></span>
          </td>
          <td>
            <%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:product) %>
          </td>
          <td><%= @post.title %></td>
          <td><%= image.alt %></td>
          <td class="actions">
            <%= link_to_with_icon 'icon-edit', t(:edit), edit_admin_post_image_url(@post, image), :no_text => true, :data => {:action => 'edit'} %>
            <%= link_to_delete image, { :url => admin_post_image_url(@post, image), :no_text => true } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/posts/images/new.html.erb
<%= form_for [:admin, @post, @image], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="new_image">
    <legend align="center"><%= t(:new_image) %></legend>

      <%= render :partial => 'form', :locals => { :f => f } %>
    
      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button t(:update), 'icon-refresh' %>
        <span class="or"><%= t(:or) %></span>
        <%= link_to_with_icon 'icon-remove', t(:cancel), admin_post_images_url(@post), :id => 'cancel_link', :class => 'button' %>
      </div>
  </fieldset>
<% end %>

<%= javascript_include_tag 'admin/images/new.js' %>