config/routes.rb
Spree::Core::Engine.routes.draw do
  
  namespace :admin do
    resource :store_settings
    resources :posts do
      resources :images, :controller => 'posts/images' do
        post :update_positions, :on => :collection
      end
      post :update_positions, :on => :collection
      get :published, :on => :member
      get :unpublished, :on => :member
    end
    
    resources :static_pages do
      resources :images, :controller => 'static_pages/images' do
        post :update_positions, :on => :collection
      end
      post :update_positions, :on => :collection
      get :published, :on => :member
      get :unpublished, :on => :member
    end
    
    resources :uploads do
      post :update_positions, :on => :collection
    end
    
    resources :taxonomy_posts do
    	collection do
    		post :update_positions
    	end
      member do
        get :get_children
      end

      resources :taxon_posts
    end

    resources :taxon_posts, :only => [] do
      collection do
        get :search
      end
    end
  end
  
  match '/contacts', :to => 'static_pages#contacts', :as => :contacts
  match '/contacts/send', :to => "static_pages#create_mail", :via => :post
  match '/p/:id', :to => 'static_pages#show', :as => :page
  match '/p', :to => 'static_pages#index', :as => :pages
  match '/blog', :to => 'posts#index', :as => :blog
  match '/news/:id', :to => 'posts#show', :as => :post
  
  # route globbing for pretty nested taxon and product paths
  match '/tp/*id', :to => 'taxon_posts#show', :as => :nested_taxon_posts
end

app/models/spree/page.rb
module Spree
  class Page < ActiveRecord::Base
    has_and_belongs_to_many :products, :join_table => 'spree_pages_products'
    has_and_belongs_to_many :taxons, :join_table => 'spree_pages_taxons'
    has_many :images, :as => :viewable, :order => :position, :dependent => :destroy
    has_many :uploads, :as => :uploadable
    
    accepts_nested_attributes_for :uploads, :allow_destroy => true
    
    make_permalink :order => :title
    
    validates_presence_of :title
    
    def to_param
      permalink.present? ? permalink : (permalink_was || title.to_s.to_url)
    end
    
    def published?
      !self.published_at.blank?
    end
    
    def self.retrive_by_taxon(taxon_id)
      Spree::Taxon.find(taxon_id).pages
    end

    def self.retrive_by_product(product_id)
      Spree::Product.find(product_id).pages
    end
    
    def link_is_blank?
      self.link.blank?
    end
  end 
end

app/models/spree/upload.rb
module Spree
  class Upload < ActiveRecord::Base
    belongs_to :uploadable, :polymorphic => true
    acts_as_list
    
    make_permalink :order => :title
    
    has_attached_file :attachment,
                      :url => '/spree/uploads/:id/:style/:basename.:extension',
                      :path => ':rails_root/public/spree/uploads/:id/:style/:basename.:extension'
    
    include Spree::Core::S3Support
    supports_s3 :attachment
    
    def to_param
      permalink.present? ? permalink : (permalink_was || title.to_s.to_url)
    end
  end
end

app/controllers/spree/admin/uploads_controller.rb
module Spree
  module Admin
    class UploadsController < ResourceController
      def index
        respond_with(@collection)
      end
      
      def show
        redirect_to( :action => :edit )
      end
      
      def destroy
        @upload = Spree::Upload.where(:permalink => params[:id]).first!
        @upload.delete

        flash.notice = I18n.t('notice_messages.upload_deleted')

        respond_with(@upload) do |format|
          format.html { redirect_to collection_url }
          format.js  { render_js_for_destroy }
        end
      end
      
      protected
      def find_resource
        Spree::Upload.find_by_permalink!(params[:id])
      end
      
      def location_after_save
        edit_admin_upload_url(@upload)
      end
      
      def collection
        return @collection if @collection.present?
        params[:q] ||= {}
        params[:q][:s] ||= "title asc"

        @search = super.ransack(params[:q])
        @collection = @search.result.page(params[:page]).per(Spree::Config[:admin_post_per_page])
      end
    end
  end
end

app/views/spree/admin/uploads/_form.html.erb
<div data-hook="admin_post_form_fields">

	<div class="left eight columns alpha" data-hook="admin_post_form_left">    
		<%= f.field_container :title do %>
			<%= f.label :title, raw(t(:title) + content_tag(:span, ' *', :class => 'required')) %>
			<%= f.text_field :title, :class => 'fullwidth title' %>
			<%= f.error_message_on :title %>
		<% end %>

		<%= f.field_container :permalink do %>
			<%= f.label :permalink, raw(t(:permalink) + content_tag(:span, ' *',  :class => "required")) %>
			<%= f.text_field :permalink, :class => 'fullwidth title' %>
			<%= f.error_message_on :permalink %>
		<% end %>

		<%= f.field_container :body do %>
			<%= f.label :body, t(:body) %>
			<%= f.text_area :body, {:rows => 20, :class => 'fullwidth'} %>
			<%= f.error_message_on :body %>
		<% end %>
	</div>

	<div class="right four columns omega" data-hook="admin_post_form_right">
		<%= f.field_container :published_at do %>
			<%= f.label :published_at, t(:published_at) %>
			<%= f.error_message_on :published_at %>
			<%= f.text_field :published_at, :value => datepicker_field_value(@post.published_at), :class => 'datepicker' %>
		<% end %>

		<div class="clear"></div>

		<%= f.field_container :from do %>
			<%= f.label :from, t(:from) %>
			<%= f.error_message_on :from %>
			<%= f.text_field :from, :value => datepicker_field_value(@post.from), :class => 'datepicker' %>
		<% end %>

		<%= f.field_container :to do %>
			<%= f.label :to, t(:to) %>
			<%= f.error_message_on :to %>
			<%= f.text_field :to, :value => datepicker_field_value(@post.to), :class => 'datepicker' %>
		<% end %>

		<div class="clear"></div>

		<%= f.field_container :publication_date_from do %>
			<%= f.label :publication_date_from, t(:publication_date_from) %>
			<%= f.error_message_on :publication_date_from %>
			<%= f.text_field :publication_date_from, :value => datepicker_field_value(@post.publication_date_from), :class => 'datepicker' %>
		<% end %>

		<%= f.field_container :publication_date_to do %>
			<%= f.label :publication_date_to, t(:publication_date_to) %>
			<%= f.error_message_on :publication_date_to %>
			<%= f.text_field :publication_date_to, :value => datepicker_field_value(@post.publication_date_to), :class => 'datepicker' %>
		<% end %>

		<%= f.field_container :product do %>
			<%= f.label :product_ids, t(:product) %>
			<%= f.collection_select(:product_ids, @products, :id, :name, { :include_blank => 'None' }, { :class => 'select2' }) %>
			<%= f.error_message_on :product %>
		<% end %>
	</div>

	<div class="twelve columns alpha omega">
		<%= f.field_container :taxons do %>
			<%= f.label :taxon_ids, t(:taxons) %><br />
			<%= f.hidden_field :taxon_ids, :value => @post.taxon_ids.join(',') %>
		<% end %>
		
		<%= f.field_container :tag_list do %>
			<%= f.label :tag_list, t(:tag_list) %><br />
			<%= f.text_field :tag_list %>
		<% end %>
	</div>

	<!-- <h2><%= t(:metadata) %></h2> -->
	<div data-hook="admin_post_form_meta" class="alpha omega twelve columns">
		<%= f.field_container :meta_keywords do %>
			<%= f.label :meta_keywords, t(:meta_keywords) %>
			<%= f.text_field :meta_keywords, :class => 'fullwidth' %>
		<% end %>

		<%= f.field_container :meta_description do %>
			<%= f.label :meta_description, t(:meta_description) %>
			<%= f.text_field :meta_description, :class => 'fullwidth' %>
		<% end %>
	</div>

	<div class="clear"></div>

	<div data-hook="admin_post_form_additional_fields"></div>

	<div class="clear"></div>
</div>

app/views/spree/admin/uploads/edit.html.erb
<% content_for :page_actions do %>
  <li><%= button_link_to t(:back_to_posts_list), admin_posts_url, :icon => 'icon-arrow-left' %></li>
  <li id="new_post_link">
    <%= button_link_to t(:new_post), new_object_url, { :remote => true, :icon => 'icon-plus', :id => 'admin_new_post' } %>
  </li>
<% end %>

<%= render :partial => 'spree/admin/shared/post_tabs', :locals => { :current => 'Post Details' } %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @post } %>

<%= form_for [:admin, @post], :method => :put, :html => { :multipart => true } do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/uploads/index.html.erb
<% content_for :page_title do %>
  <%= t(:listing_uploads) %>
<% end %>

<% content_for :page_actions do %>
<div class="toolbar" data-hook="toolbar">
	<ul class="actions header-action-links inline-menu">
      	<li id="new_upload_link">
			<%= button_link_to t(:new_upload), new_object_url, { :remote => true, :icon => 'icon-plus', :id => 'admin_upload_post' } %>
		</li>
	</ul>
	<br class="clear" />
</div>
<% end %>

<% content_for :table_filter_title do %>
	<%= t(:search) %>
<% end %>

<% content_for :table_filter do %>
<div data-hook="admin_uploads_sidebar">
	<%= search_form_for [:admin, @search] do |f| %>      
	<%- locals = {:f => f} %>
	<div data-hook="admin_uploads_index_search">
		<div class="alpha five columns">
			<div class="field">
				<%= f.label :title_cont, t(:title) %>
				<%= f.text_field :title_cont, :size => 15 %>
			</div>  
		</div>
		<div class="five columns">
			<div class="field">
				<%= f.label :presentation_cont, t(:presentation) %>
				<%= f.text_field :presentation_cont, :size => 15 %>
			</div>
		</div>
	</div>
	<div class="clear"></div>
	<div class="form-buttons actions filter-actions" data-hook="admin_uploads_index_search_buttons">
		<%= button t(:search), 'icon-search' %>
	</div>
	<% end %>
</div>
<% end %>

<div id="new_upload" data-hook></div>

<table class="index sortable" id="listing_uploads" data-hook data-sortable-link="<%= update_positions_admin_uploads_url %>">
	<colgroup>
       <col style="width: 15%;">
       <col style="width: 32%;">
       <col style="width: 15%;">
	   <col style="width: 15%;">
       <col style="width: 17%;">
    </colgroup>
	<thead>
		<tr data-hook="admin_uploads_index_headers">
			<th><%= sort_link @search, :title, t(:title, :scope => 'activerecord.attributes.spree/upload') %></th>
			<th><%= t(:presentation) %></th>
			<th><%= t(:attachment, :scope => 'activerecord.attributes.spree/upload') %></th>
			<th data-hook="admin_uploads_index_header_actions" class="actions"></th>
		</tr>
	</thead>
	<tbody>
		<% @collection.each do |upload|%>
		<tr id="<%= spree_dom_id upload %>" data-hook="admin_uploads_index_rows">
			<td width="270px" class='post_title'>
				<span class="handle"></span>
				<%= upload.title %>
			</td>
			<td><%= truncate(upload.presentation, :length => 150, :omission => '...') %></td>
			<td><%= link_to(upload.attachment_file_name, upload.attachment.url) rescue "" %></td>
			<td class="actions" data-hook="admin_posts_index_row_actions">
				<%= link_to_edit upload, :no_text => true, :class => 'edit' %>
				&nbsp;
				<%= link_to_delete upload, :no_text => true %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

<%= paginate @collection %>

app/views/spree/admin/uploads/new.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @post } %>

<%= form_for [:admin, @post], :html => { :multipart => true } do |f| %>
<fieldset data-hook="new_post">
	<legend align="center"><%= t(:new_post) %></legend>
	<div data-hook="new_post_attrs" class="row">
		<div class="left alpha eleven columns">
			<%= f.field_container :title do %>
				<%= f.label :title, t(:title) %> <span class="required">*</span><br />
				<%= f.text_field :title, :class => 'fullwidth title' %>
				<%= f.error_message_on :title %>
			<% end %>

			<%= f.field_container :body do %>
				<%= f.label :body, t(:body) %><br />
				<%= f.text_area :body, {:rows => 20, :class => 'fullwidth'} %>
				<%= f.error_message_on :body %>
			<% end %>  
		</div>

		<div class="right four columns">
			<%= f.field_container :from do %>
				<%= f.label :from, t(:from) %><br />
				<%= f.text_field :from, :class => 'datepicker fullwidth' %>
				<%= f.error_message_on :from %>
			<% end %>
			
			<%= f.field_container :to do %>
				<%= f.label :to, t(:to) %> <span class="required">*</span><br />
				<%= f.text_field :to, :class => 'datepicker fullwidth' %>
				<%= f.error_message_on :to %>
			<% end %>
			
			<div class="clear"></div>
			
			<%= f.field_container :product do %>
		      <%= f.label :product_ids, t(:product) %><br />
		      <%= f.collection_select(:product_ids, @products, :id, :name, { :include_blank => 'None' }, { :class => 'select2' }) %>
		      <%= f.error_message_on :product %>
		    <% end %>
			
			<div class="clear"></div>
			
			<%= f.field_container :taxons do %>
		      <%= f.label :taxon_ids, t(:taxons) %><br />
		      <%= f.hidden_field :taxon_ids, :value => @post.taxon_ids.join(',') %>
		    <% end %>
		</div>

		<div class="right omega four columns">
			<%= f.field_container :published_at do %>
			<%= f.label :published_at, t(:published_at) %>
			<%= f.error_message_on :published_at %>
			<%= f.text_field :published_at, :class => 'datepicker fullwidth' %>
			<% end %>
		</div>
	</div>
  <%= render :partial => 'spree/admin/shared/new_resource_links' %>
</fieldset>
<% end %>

app/views/spree/admin/uploads/new.js.erb
$("#new_post").html('<%= escape_javascript(render :template => "spree/admin/posts/new", :formats => [:html], :handlers => [:erb]) %>');
handle_date_picker_fields();
<% unless Rails.env.test? %>
  $('.select2').select2();
<% end %>
$("#table-filter").hide();
$("#admin_new_post").parent().hide();

if ($("#post_taxon_ids").length > 0) {
	$("#post_taxon_ids").select2({
		placeholder: Spree.translations.taxon_placeholder,
		multiple: true,
		initSelection: function(element, callback) {
			return $.getJSON(Spree.routes.taxon_search + "?ids=" + (element.val()), null, function(data) {
				return callback(self.cleanTaxons(data));
			});
		},
		ajax: {
			url: Spree.routes.taxon_search,
			datatype: 'json',
			data: function(term, page) {
				return { q: term }
			},
			results: function (data, page) {
				return { results: self.cleanTaxons(data) }
			}
		},
		formatResult: function(taxon) {
			return taxon.pretty_name
		},
		formatSelection: function(taxon) {
			return taxon.pretty_name
		}
	});
}