config/routes.rb
Spree::Core::Engine.routes.draw do
  
  namespace :admin do
    resource :store_settings
    resources :posts do
      resources :images, :controller => 'posts/images' do
        post :update_positions, :on => :collection
      end
      post :update_positions, :on => :collection
      get :published, :on => :member
      get :unpublished, :on => :member
    end
    
    resources :static_pages do
      resources :images, :controller => 'static_pages/images' do
        post :update_positions, :on => :collection
      end
      post :update_positions, :on => :collection
      get :published, :on => :member
      get :unpublished, :on => :member
    end
    
    resources :uploads do
      post :update_positions, :on => :collection
    end
    
    resources :taxonomy_posts do
    	collection do
    		post :update_positions
    	end
      member do
        get :get_children
      end

      resources :taxon_posts
    end

    resources :taxon_posts, :only => [] do
      collection do
        get :search
      end
    end
  end
  
  match '/contacts', :to => 'static_pages#contacts', :as => :contacts
  match '/contacts/send', :to => "static_pages#create_mail", :via => :post
  match '/p/:id', :to => 'static_pages#show', :as => :page
  match '/p', :to => 'static_pages#index', :as => :pages
  match '/blog', :to => 'posts#index', :as => :blog
  match '/news/:id', :to => 'posts#show', :as => :post
  
  # route globbing for pretty nested taxon and product paths
  match '/tp/*id', :to => 'taxon_posts#show', :as => :nested_taxon_posts
end

app/views/spree/admin/shared/_post_tabs.html.erb
<% content_for :page_title do %>
  <%= t(:editing_post) %> &ldquo;<%= @post.title %>&rdquo;
<% end %>

<% content_for :sidebar_title do %>
  <span class="title"><%= @post.title %></span>
<% end %>

<% content_for :sidebar do %>
  <nav class="menu">
    <ul data-hook="admin_post_tabs">
      <li<%== ' class="active"' if current == 'Post Details' %>>
        <%= link_to_with_icon 'icon-edit', t(:post_details), edit_admin_post_url(@post) %>
      </li>
      <li<%== ' class="active"' if current == 'Images' %>>
        <%= link_to_with_icon 'icon-picture', t(:images), admin_post_images_url(@post) %>
      </li>
    </ul>
  </nav>

<% end %>

app/views/spree/admin/shared/_static_page_tabs.html.erb
<% content_for :page_title do %>
  <%= t(:editing_static_page) %> &ldquo;<%= @static_page.title %>&rdquo;
<% end %>

<% content_for :sidebar_title do %>
  <span class="title"><%= @static_page.title %></span>
<% end %>

<% content_for :sidebar do %>
  <nav class="menu">
    <ul data-hook="admin_static_page_tabs">
      <li<%== ' class="active"' if current == 'Static Page Details' %>>
        <%= link_to_with_icon 'icon-edit', t(:static_page_details), edit_admin_static_page_url(@static_page) %>
      </li>
      <li<%== ' class="active"' if current == 'Images' %>>
        <%= link_to_with_icon 'icon-picture', t(:images), admin_static_page_images_url(@static_page) %>
      </li>
    </ul>
  </nav>

<% end %>

app/views/spree/admin/shared/_store_setting_configurations_menu.html.erb
<tr>
  <td><%= link_to t(:store_settings), admin_store_settings_url %></td>
  <td><%= t(:store_settings_description) %></td>
</tr>